/**
 * Prometheus Metrics Definitions for FlowLint
 *
 * This module defines all custom Prometheus metrics for FlowLint observability.
 * Metrics follow Prometheus naming conventions and are designed for low cardinality.
 *
 * @module packages/observability/metrics
 */

import { Registry, Counter, Histogram, Gauge, collectDefaultMetrics } from 'prom-client';

// Create dedicated registry for FlowLint metrics
export const register = new Registry();

// Enable default process and Node.js metrics
collectDefaultMetrics({ register });

// ============================================================================
// Custom Application Metrics
// ============================================================================

/**
 * Metric 1: Webhook Counter
 *
 * Tracks total webhooks received from GitHub, labeled by event type and action.
 *
 * Example usage:
 *   webhookCounter.labels('pull_request', 'opened').inc();
 */
export const webhookCounter = new Counter({
  name: 'flowlint_webhook_received_total',
  help: 'Total number of webhooks received from GitHub',
  labelNames: ['event_type', 'action'],
  registers: [register]
});

/**
 * Metric 2: Jobs Queued Counter
 *
 * Tracks total review jobs added to BullMQ queue.
 *
 * Example usage:
 *   jobsQueuedCounter.labels('acme-corp/api-gateway').inc();
 */
export const jobsQueuedCounter = new Counter({
  name: 'flowlint_jobs_queued_total',
  help: 'Total number of review jobs queued for processing',
  labelNames: ['repo'],
  registers: [register]
});

/**
 * Metric 3: Jobs Completed Counter
 *
 * Tracks total review jobs completed (success or failure).
 *
 * Example usage:
 *   jobsCompletedCounter.labels('success', 'acme-corp/api-gateway').inc();
 */
export const jobsCompletedCounter = new Counter({
  name: 'flowlint_jobs_completed_total',
  help: 'Total number of review jobs completed',
  labelNames: ['status', 'repo'],
  registers: [register]
});

/**
 * Metric 4: Job Duration Histogram
 *
 * Distribution of job processing time in seconds.
 * Buckets optimized for typical workflow review times (0.1s to 120s).
 *
 * Example usage:
 *   const timer = jobDurationHistogram.startTimer({ repo: 'acme-corp/api-gateway' });
 *   // ... process job
 *   timer(); // Records duration
 */
export const jobDurationHistogram = new Histogram({
  name: 'flowlint_job_duration_seconds',
  help: 'Duration of job processing in seconds',
  labelNames: ['repo'],
  buckets: [0.1, 0.5, 1, 2, 5, 10, 30, 60, 120],
  registers: [register]
});

/**
 * Metric 5: Queue Depth Gauge
 *
 * Current number of jobs in queue by state.
 * Updated periodically by collector (every 10 seconds).
 *
 * Example usage:
 *   queueDepthGauge.set({ state: 'waiting' }, 10);
 */
export const queueDepthGauge = new Gauge({
  name: 'flowlint_queue_depth',
  help: 'Current number of jobs in queue by state',
  labelNames: ['state'],
  registers: [register]
});

/**
 * Metric 6: GitHub API Calls Counter
 *
 * Tracks GitHub API calls made by FlowLint, labeled by method and status.
 *
 * Example usage:
 *   githubApiCallsCounter.labels('GET', '200', '/repos/:owner/:repo/pulls/:number/files').inc();
 */
export const githubApiCallsCounter = new Counter({
  name: 'flowlint_github_api_calls_total',
  help: 'Total GitHub API calls made by FlowLint',
  labelNames: ['method', 'status', 'endpoint'],
  registers: [register]
});

/**
 * Metric 7: Findings Generated Counter
 *
 * Tracks lint findings generated, labeled by rule and severity.
 *
 * Example usage:
 *   findingsGeneratedCounter.labels('rate_limit_retry', 'must').inc();
 */
export const findingsGeneratedCounter = new Counter({
  name: 'flowlint_findings_generated_total',
  help: 'Total lint findings generated by rule and severity',
  labelNames: ['rule', 'severity'],
  registers: [register]
});

/**
 * Metric 8: Redis Operations Counter (Optional)
 *
 * Tracks Redis operations performed by BullMQ.
 *
 * Example usage:
 *   redisOpsCounter.labels('zadd', 'success').inc();
 */
export const redisOpsCounter = new Counter({
  name: 'flowlint_redis_operations_total',
  help: 'Total Redis operations performed',
  labelNames: ['operation', 'status'],
  registers: [register]
});

// ============================================================================
// HTTP Metrics (Automatic via middleware)
// ============================================================================

/**
 * HTTP Request Duration Histogram
 *
 * Automatically populated by metricsMiddleware.
 * Tracks HTTP request latency by method, route, and status.
 */
export const httpRequestDuration = new Histogram({
  name: 'http_request_duration_seconds',
  help: 'Duration of HTTP requests in seconds',
  labelNames: ['method', 'route', 'status'],
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5],
  registers: [register]
});

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Get all metrics in Prometheus exposition format
 *
 * @returns Prometheus-formatted metrics string
 */
export async function getMetrics(): Promise<string> {
  return register.metrics();
}

/**
 * Get metrics content type header
 *
 * @returns Prometheus content type string
 */
export function getContentType(): string {
  return register.contentType;
}

/**
 * Clear all metrics (useful for testing)
 *
 * WARNING: This removes all metrics from the registry.
 * Only use in test environments.
 */
export function clearMetrics(): void {
  register.clear();
}

/**
 * Get single metric by name (for testing)
 *
 * @param name - Metric name
 * @returns Metric instance or undefined
 */
export function getMetric(name: string) {
  return register.getSingleMetric(name);
}
