import OpenAI from 'openai';
import { Octokit } from '@octokit/rest';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const TAG_NAME = process.env.TAG_NAME;
// GITHUB_REPOSITORY is provided by Actions, e.g. 'owner/repo'
const [OWNER, REPO] = (process.env.GITHUB_REPOSITORY || '').split('/');

if (!OPENAI_API_KEY || !GITHUB_TOKEN || !TAG_NAME || !OWNER || !REPO) {
  console.error('Missing required environment variables.');
  process.exit(1);
}

const openai = new OpenAI({ apiKey: OPENAI_API_KEY });
const octokit = new Octokit({ auth: GITHUB_TOKEN });

async function main() {
  try {
    console.log(`Fetching release ${TAG_NAME} for ${OWNER}/${REPO}...`);
    const release = await octokit.repos.getReleaseByTag({
      owner: OWNER,
      repo: REPO,
      tag: TAG_NAME as string,
    });

    const originalNotes = release.data.body || '';
    console.log('Original Notes Length:', originalNotes.length);

    const prompt = `
You are a Developer Relations expert. Your task is to polish the Release Notes for a software product.

Input Release Notes:
"""
${originalNotes}
"""

Instructions:
1.  **Filter Noise:** Remove lines about internal CI chores, test updates, refactoring, or minor dependency bumps. Keep user-facing features and bug fixes.

   **CRITICAL: @replikanti/flowlint-core upgrades must ALWAYS be mentioned:**
   - If you see any mention of "@replikanti/flowlint-core" being updated (any version change), you MUST include it in the release notes
   - Extract the version numbers (e.g., "0.7.1 → 0.8.0" or just "→ 0.8.0" if old version unknown)
   - Add it under a "📦 Core Library" or "⚡ Improvements" section
   - Format: "Updated to @replikanti/flowlint-core v0.8.0" or "Core library upgraded to v0.8.0"
   - Even if no other details are available about what changed in core, still mention the upgrade

2.  **Rewrite & Group:** Group items into clear sections: "🚀 New Features", "🐛 Bug Fixes", "⚡ Improvements", "📦 Dependencies". Use emojis. If flowlint-core was upgraded, it goes in "⚡ Improvements" or its own "📦 Core Library" section.
3.  **Tone:** Professional, exciting, concise.
4.  **Summary:** Add a one-sentence summary at the top (e.g., "This release brings performance improvements and fixes 3 bugs."). If flowlint-core was upgraded, mention it in the summary (e.g., "This release upgrades to core v0.8.0 and fixes 2 bugs.").
5.  **Output:** Return ONLY the Markdown content of the new release notes.
`;

    console.log('Asking AI to polish notes...');
    const response = await openai.chat.completions.create({
      model: 'gpt-5.1',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.2,
    });

    const newNotes = response.choices[0].message.content?.trim();

    if (newNotes && newNotes !== originalNotes) {
      console.log('Updating release notes on GitHub...');
      await octokit.repos.updateRelease({
        owner: OWNER,
        repo: REPO,
        release_id: release.data.id,
        body: newNotes,
      });
      console.log('Release notes updated successfully.');
    } else {
      console.log('No changes generated by AI or empty response.');
    }

  } catch (error) {
    console.error('Error polishing release notes:', error);
    process.exit(1);
  }
}

main();
